spring.application.name=rabs-restaurant-website
spring.data.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@rabs-restaurant-cluster.ajgblpa.mongodb.net/RabsRestaurantDB?retryWrites=true&w=majority

mongock.migration-scan-package=com.project.rabs.restaurant.website.migrations

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/RabzRealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol.openid-connect/certs
server.port=8081